---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "latest"

inputs:
  - name: cf-shell-release
  - name: version

outputs:
  - name: cf-shell-new-version

run:
  path: cf-shell-release/ci/scripts/create-release-version.sh